### PR TITLE
Keras 0.3.2 compatibility and better RMSE

### PR DESCRIPTION
**Pull request by GregorySenay**
Hi @jamesmf,
I make quicks modifications to be fully compatible with Keras 0.3.2 without any additional or extra layers.
You can verify it but the model provides better RMSE.
If you are okay, it can be a very good example to be integrated in Keras? What do you think?
Thx,

### CODE REVIEW

**Comment by jamesmf** [comment]
This looks great, thanks for the update. I'd be happy to have it be an example if that's useful.

**Comment by GregorySenay** [comment]
Great @jamesmf !
Did you also verify the RMSE value with this model? Normally it's better, if you do it, It will make a second check for this model. 
And can you update the README with the new values if you do it?

**Comment by jamesmf** [comment]
Updated README, the RMSE improved slightly.

**Comment by GregorySenay** [comment]
Great ! Thanks for confirm it

**Pull request merged**
